# TRAINING PARAMS
LEARNING_RATE = 3e-4
NUM_STEPS = 500
DROPOUT = 0.2

# MODEL PARAMS
EMBEDDING_SIZE = 384    # C
BATCH_SIZE = 64         # B
BLOCK_SIZE = 256        # T (lookbehind distance)
HEAD_SIZE = 64          # H (should be less than EMBEDDING_SIZE)
NUM_HEADS = 6           # N
NUM_LAYERS = 6

# DATA PARAMS
VOCAB_SIZE = 65         # V
TRAIN_VAL_SPLIT = 0.9

# LOGGING PARAMS
LOSS_EVAL_ITERS = 200
LOSS_EVAL_INTERVAL = 1
